import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import List from '../components/list'
import { BrowserRouter, Routes, Route } from 'react-router-dom';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Trading Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <meta name="description" content="" />
      <meta name="author" content="" />
      <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico" />

      <title>Trading Ideas</title>

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

      <link href="album.css" rel="stylesheet" />
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" async />
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" async /> 
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" async />

      </Head>
    </div>
  )
}

